aug:
  image_aug: true
  masked_language_model: true
backbone: vgg19_bn
cnn:
  hidden: 256
  ks:
    - - 2
      - 2
    - - 2
      - 2
    - - 2
      - 1
    - - 2
      - 1
    - - 1
      - 1
  pretrained: true
  ss:
    - - 2
      - 2
    - - 2
      - 2
    - - 2
      - 1
    - - 2
      - 1
    - - 1
      - 1
dataloader:
  num_workers: 3
  pin_memory: true
dataset:
  data_root: .
  image_height: 80
  image_max_width: 300
  image_min_width: 100
  name: captchapredict
  train_annotation: train_annotation.txt
  valid_annotation: valid_annotation.txt
device: cuda:0
optimizer:
  max_lr: 0.0003
  pct_start: 0.1
predictor:
  beamsearch: false
pretrain:
  cached: /tmp/tranformerorc.pth
  id_or_url: 13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
  md5: af6b46e9295eb1c27ca90bddf8c8729a
quiet: false
seq_modeling: transformer
trainer:
  batch_size: 32
  checkpoint: ./checkpoint/transformerocr_checkpoint.pth
  export: ./weights.pth
  iters: 20000
  log: ./train.log
  metrics: 100
  print_every: 200
  valid_every: 20001
transformer:
  d_model: 256
  dim_feedforward: 2048
  max_seq_length: 1024
  nhead: 8
  num_decoder_layers: 6
  num_encoder_layers: 6
  pos_dropout: 0.1
  trans_dropout: 0.1
vocab: 0123456789
weights: https://drive.google.com/uc?id=13327Y1tz1ohsm5YZMyXVMPIOjoOA0OaA
